[package]
name = "test_usage"
version = "0.1.0"
authors = ["Loïc Lecrenier <loic.lecrenier@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
decent-serde-json-derive-alternative = { path = ".." }
decent-serde-json-alternative = { path = "../../decent-serde-json-alternative" }
json = "0.12"
